adder: adder.v
	iverilog -o adder adder.v

counter: counter.v
	iverilog -o counter counter.v

signext: signext.v
	iverilog -o signext signext.v

alu: alu.v
	iverilog -o alu alu.v

clean:
	find . -perm +100 -type f -delete


