adder: adder.v
	iverilog -o adder adder.v

counter: counter.v
	iverilog -o counter counter.v

signext: signext.v
	iverilog -o signext signext.v

alu: alu.v
	iverilog -o alu alu.v

data_memory: data_memory.v
	iverilog -o data_memory data_memory.v

instr_memory: instr_memory.v
	iverilog -o instr_memory instr_memory.v

registers: registers.v
	iverilog -o registers registers.v

controls: controls.v
	iverilog -o controls controls.v

program_counter: program_counter.v
	iverilog -o program_counter program_counter.v

clean:
	find . -perm +100 -type f -delete


